direction: down

classes: {
  node_txt: {
    style.font-size: 50
  }
  edge_txt: {
    style.font-size: 50
  }
}

Input: Ecosystem Metadata (PyPI) {
  shape: cylinder
  class: node_txt
}

Preprocessing: Data Preparation {
  class: node_txt
  style.fill: "#f3f4f6"
  extract: Extract licenses/FTLFs {class: node_txt}
  normalize: Normalize &\nDeduplicate {class: node_txt}

  extract -> normalize: {class: edge_txt}
}

Pipeline: Mapping Pipeline {
  class: node_txt
  style.fill: "#e0f2fe"

  filter: 1. Discard Invalid Labels {class: node_txt}
  exact: 2. Exact Rule-based Matching {class: node_txt}
  family: 3. License Family Heuristics {class: node_txt}
  fuzzy: 4. Approximate Text Matching {class: node_txt}

  filter -> exact: Unmatched {class: edge_txt}
  exact -> family: Unmatched {class: edge_txt}
  family -> fuzzy: Unmatched {class: edge_txt}
}

Output: Classification Results {
  class: node_txt
  shape: document
  style.fill: "#ecfeff"

  spdx: Standardized SPDX\nIdentifiers {class: node_txt}
  unresolved: Unresolved or\nCustom Licenses {class: node_txt}
}

Input -> Preprocessing.extract
Preprocessing.normalize -> Pipeline.filter: Normalized FTLFs {class: edge_txt}

Pipeline.filter -> Output.unresolved: Confirmed Unknown {class: edge_txt}
Pipeline.exact -> Output.spdx: Matched {class: edge_txt}
Pipeline.family -> Output.spdx: Matched {class: edge_txt}
Pipeline.fuzzy -> Output.spdx
Pipeline.fuzzy -> Output.unresolved: Low Confidence Match {class: edge_txt}
